language: php
sudo: false
php:
  - hhvm

before_install:
  - composer install
  - npm install -g dredd

before_script:
  - mysql -e 'create database nhlstats'
  - php artisan migrate
  - php artisan db:seed

services:
  - redis-server

script:
  # - hhvm vendor/bin/phpunit
  - cd public/doc && dredd APIDoc.md
