language: php
sudo: false

php:
  - '7.0'

before_install:
  - composer install
  - npm install -g dredd

before_script:
  - mysql -e 'create database nhlstats'
  - php artisan migrate --force
  - php artisan db:seed --force

services:
  - redis-server

script:
  - vendor/bin/phpunit
  - cd public/doc && dredd APIDoc.md
