language: php
sudo: required
dist: trusty

php:
  - '7.0'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6
  - composer install
  # - npm install -g dredd

before_script:
  - mysql -u root -e 'create database nhlstats'
  - php artisan migrate --force
  - php artisan db:seed --force

services:
  - redis-server

script:
  - composer test
  # - cd public/doc && dredd APIDoc.md
