language: php
php:
  - hhvm

before_install:
  - composer install

before_script:
  - mysql -e 'create database nhlstats'
  - php artisan migrate
  - php artisan db:seed

services:
  - redis-server

script:
  - hhvm vendor/bin/phpunit
